# Generated by Django 5.1.1 on 2024-10-01 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandsFood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FoodInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('all_quantity', models.IntegerField()),
                ('buy_total_value', models.FloatField()),
                ('sell_total_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetFoods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('animal', models.CharField(choices=[('dog', 'Cão'), ('cat', 'Gato')], max_length=5)),
                ('name', models.CharField(max_length=500)),
                ('weight', models.FloatField(choices=[(7.5, '7.5'), (10.1, '10.1'), (14.1, '14.1'), (15.1, '15.1'), (18.1, '18.1'), (20.1, '20.1'), (25.1, '25.1')])),
                ('buy_price', models.FloatField(blank=True, null=True)),
                ('sell_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('quantity_alert', models.IntegerField()),
                ('food_photo', models.ImageField(blank=True, null=True, upload_to='foods/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_food', to='Storage.brandsfood')),
            ],
        ),
    ]
