# Generated by Django 5.1.1 on 2024-09-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petfoods',
            name='food_photo',
            field=models.ImageField(blank=True, null=True, upload_to='projetodev/'),
        ),
    ]
