# Generated by Django 5.1.1 on 2024-10-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodinventory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='foodinventory',
            old_name='buy_total_value',
            new_name='buy_value',
        ),
        migrations.RenameField(
            model_name='foodinventory',
            old_name='sell_total_value',
            new_name='sell_value',
        ),
    ]
