# Generated by Django 5.1.1 on 2024-10-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0003_storagetransitions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petfoods',
            old_name='sell_price',
            new_name='sell_price_cred',
        ),
        migrations.AddField(
            model_name='petfoods',
            name='sell_price_dinh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
