# Generated by Django 5.1.1 on 2024-10-25 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_onwer', models.CharField(max_length=200)),
                ('pla_phone', models.CharField(max_length=16)),
                ('plan_pet', models.CharField(max_length=200)),
                ('bath1', models.DateField(blank=True, null=True)),
                ('bath2', models.DateField(blank=True, null=True)),
                ('bath3', models.DateField(blank=True, null=True)),
                ('bath4', models.DateField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandartWorks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AllPets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('onwer', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=16)),
                ('pet', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('warnings', models.TextField(blank=True, max_length=1000, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimentos', to='Bath.standartworks')),
            ],
        ),
    ]
