# Generated by Django 5.1.1 on 2024-10-25 23:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bath', '0002_alter_allpets_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpets',
            name='race',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyplans',
            name='plan_race',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
