# Generated by Django 5.1.1 on 2024-10-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bath', '0003_allpets_race_monthlyplans_plan_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpets',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
