# Generated by Django 5.1.1 on 2024-10-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bath', '0005_rename_pla_phone_monthlyplans_plan_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpets',
            name='onwer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='allpets',
            name='race',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
